### ISSUE TITLE
Add tick time to actions

### ISSUE THREAD

**Issue by jrhackett** [jrhackett/swarm-af#15]
We should add a tick time to actions to convey the number of ticks needed to complete an action. Every tick an agent spends trying to do an action will decrement the count.

Movement will be an interesting choice here. If an agent wants to travel to a cell outside of their range, should we create several actions or keep one and adjust the tick time accordingly?

**Comment by dombozzuto** [comment]
I'm unfamiliar w/ github issues but I think i resolved this with the PR mentioned above, not sure if theres a proper way to tie this together

**Comment by jrhackett** [comment]
Referencing the issue in the PR should be enough. After the PR is approved, you can close the issue. I'll close this now since I'm approving #26.
